CREATE TABLE master_data (
    id BIGSERIAL PRIMARY KEY,
    timestamp TIMESTAMPTZ,
    hour INTEGER,
    date INTEGER,
    month TEXT,  -- Changed from INTEGER to TEXT for JAN, FEB, etc.
    year INTEGER,
    branch_code TEXT,
    branch_name TEXT,
    district_name TEXT,
    region_name TEXT,
    product_id TEXT,
    account_id TEXT,
    center_name TEXT,
    center_id TEXT,
    client_name TEXT,
    client_id TEXT,
    employee_id TEXT,
    employee_name TEXT,
    db_date DATE,
    db_amount NUMERIC(15, 2),
    meeting_date DATE,
    dpd_group_last_month TEXT,
    dpd_group_present TEXT,
    regular_demand_account INTEGER,
    regular_demand_amount NUMERIC(15, 2),
    od_demand_account INTEGER,
    od_demand_amount NUMERIC(15, 2),
    total_demand_account INTEGER,
    total_demand_amount NUMERIC(15, 2),
    achievement_account INTEGER,
    achievement_amount NUMERIC(15, 2),
    portfolio_account INTEGER,
    portfolio_amount NUMERIC(15, 2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
